dist: xenial
language: python

python:
  - "3.7"

cache: pip

addons:
  chrome: stable

install:
  - pip install -r requirements.txt

before_script:
  - docker-compose -f supporting.yml up -d
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest --cov=programdom --cov-report xml:coverage.xml tests/

after_script:
  - ./cc-test-reporter after-build --id b99c3291b5f5f531ea098cdb806a1f0e9e7a45bcc59858dd18962ec3029300b9 --exit-code $TRAVIS_TEST_RESULT
  - docker-compose -f supporting.yml down

