version: '3'

volumes:
  prod_postgres_data: {}
  static_files: {}
  buckets: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - redis
      - bridge
      - minio
    volumes:
      - static_files:/static
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
      - .envs/.prod/.redis
      - .envs/.prod/.minio
    expose:
      - "8000"
    command: /start
    restart: on-failure

  bridge:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
      - .envs/.prod/.redis
      - .envs/.prod/.minio
    depends_on:
      - redis
      - postgres
      - judgezero
    command: python manage.py runworker judgebridge
    restart: on-failure

  postgres:
    image:
      postgres:11-alpine
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .envs/.prod/.postgres
    restart: on-failure

  judgezero:
    image: judge0/api
    expose:
      - "3000"
    env_file:
      - .envs/.prod/.judge0
      - .envs/.prod/.redis
      - .envs/.prod/.postgres
    restart: on-failure

  worker:
    image: judge0/api
    env_file:
      - .envs/.prod/.judge0
      - .envs/.prod/.redis
      - .envs/.prod/.postgres
    command: bash -c "while true; do rails resque:work; done"
    privileged: true
    restart: on-failure



  redis:
    image:
      redis:5-alpine
    expose:
      - "6379"
    restart: on-failure

  rev-proxy:
    image: nginx
    depends_on:
      - minio
      - django
    volumes:
      - ./compose/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: on-failure

  minio:
    image: minio/minio:RELEASE.2019-04-23T23-50-36Z
    volumes:
      - buckets:/data
    expose:
      - "9000"
    env_file:
      - .envs/.prod/.minio
    command: server /data
    restart: on-failure
