version: '3'

volumes:
  local_postgres_data: {}


services:
  postgres:
    image:
      postgres:11-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image:
      redis:5-alpine
    ports:
      - "6379:6379"
