version: '3'

volumes:
  local_postgres_data: {}


services:
  postgres:
    image:
      postgres:11-alpine
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .envs/.local/.postgres


  judgezero:
    image: judge0/api
    ports:
      - "3000:3000"
    env_file:
      - .envs/.local/.judge0
      - .envs/.local/.redis
      - .envs/.local/.postgres


  redis:
    image:
      redis:5-alpine
    ports:
      - "6379:6379"
