# Generated by Django 2.1.7 on 2019-03-15 15:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programdom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
