# Generated by Django 2.1.7 on 2019-04-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtest',
            name='name',
            field=models.CharField(default='New Test', max_length=100),
        ),
    ]
