# Generated by Django 2.1.7 on 2019-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programdom', '0002_auto_20190303_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='skeleton',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
